name: cxone
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx AST Github Action
      # You may pin to the exact commit or the version.
       #uses: Checkmarx/ast-github-action@749fec53e0db0f6404a97e2e0807c3e80e3583a7
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          # Provide the AST portal URL
          base_uri: https://ind.iam.checkmarx.net/

          # Provide the Tenant for AST portal URL
          cx_tenant: ama-partners

          # Client ID for AST portal authentication
          cx_client_id: ME123_CxOne_Client
 
          # Secret key for AST portal authentication
          cx_client_secret: BQHNkrH9QleEGjTuwdAv8hoJNrFFO6Pm

          # Select a Checkmarx Project Name
          project_name: ME_Velu_NodeGoat

          # Branch name
          #branch: master

          # Additional parameters for AST scan
          additional_params: --report-format sarif --output-path . --output-name cx_result
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with: 
        # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif

# Repository name for PR decoration
# repo_name: # optional, default is ${{ github.event.repository.name }}
# Organization name to create the Pr comment
# namespace: # optional, default is ${{ github.repository_owner }}
# Pr Number of the pull request that needs the decoration
# pr_number: # optional, default is ${{ github.event.number }}
          
